### ISSUE TITLE
How to know text and pointer text file?

### ISSUE THREAD

**Issue by ghost** [gdkchan/HDATextTool#11]
I'm not programmer so i don't know how to know file. bin containing text and pointer of the text? can you explain to me?

**Comment by gdkchan** [comment]
The readme has instructions, from what I recall all the HDA files starting with "EVTMSG" contains text.

**Comment by ghost** [comment]
After you extract HDA files, you'll get a bunch of bin files. You say "It is usually (but no always!) the file right after the text. So if "File_00001.bin" have text, "File_00002.bin" is the pointers for that text."

Is it just guess? Is there a specific and easy way to find out this?

**Comment by ghost** [comment]
And you say "After, go to your image editing software, and locate the LBA of the file you modified. After this, look the new size of the file you modified"

Since i'm not programmer, i dunno how to ''locate LBA file and new size of the file you modified'. Can you explain to me the simplest way?

**Comment by ghost** [comment]
And and, where is general dialogues? in CHARA folder, isn't it? EVENT Folder only contain event text, right?
