### ISSUE TITLE
Locate LBA File

### ISSUE THREAD

**Issue by ghost** [gdkchan/HDATextTool#12]
How to locate LBA file?

**Comment by gdkchan** [comment]
Open the game image file on a tool that shows the LBA, such as CDmage.

**Comment by ghost** [comment]
Thank now, now i get it.

But something is missing. EVENT Folder only contain event script file. The other like daily dialogues, where is it? i didn't find it.

And something weird again, EVTMSG14 Folder file, cannot be converted to script txt. I already use all possible pattern, but txt is the same. Blank

**Comment by ghost** [comment]
And what tool software for replace HDA? can't with CDMage
