### ISSUE TITLE
Compressor for files inside .HDA?

### ISSUE THREAD

**Issue by ghost** [gdkchan/HDATextTool#18]
The game has maximum memory limit for some files, if the file is too big sometimes the game has issues or crashes. I just wanted to ask you, can you please make compressor for files? Thanks in advance.

**Comment by dyz868** [comment]
Sorry, if I'm bothering you..

**Comment by ghost** [comment]
I actually found a workaround just made dummy, made file bigger, and it works, don't know its actually limit or not, its weird though..
