### ISSUE TITLE
I have trouble fixing ELF LBA table

### ISSUE THREAD

**Issue by Species-8472** [gdkchan/HDATextTool#2]
Excuse me, can you please tell me how to fix ELF, because I have trouble writing decimals. And can you explain me what is LBA? For EX. I have write "HDATextTool -fixelf SLUS_202.51 1.455 706.848", and it trows error Unhandled Exception: System.Format.Exception: Input string was not in a correct format. Can you tell me please what do you mean about writing all in decimals?

**Comment by gdkchan** [comment]
you shouldn't place dots on the number. Like 1.455 should be 1455 etc.

**Comment by Species-8472** [comment]
Thank you!
