### ISSUE TITLE
Can you please update HDATextTool?

### ISSUE THREAD

**Issue by Species-8472** [gdkchan/HDATextTool#3]
It's cool that HDATextTool can export texts, but I'd like to export music, models and textures from Harvest Moon, so can you update it, that it can change music or models?

**Comment by gdkchan** [comment]
No because it would be too much work to reverse and support every single format that the game uses, like it would take several days or maybe weeks most likely, so I don't have interest in doing this atm sorry.

**Comment by Species-8472** [comment]
Ok, tell me when you think that you have interest, I love that game too. Btw. can you tell me which program did you use to create this Program?

**Comment by Species-8472** [comment]
Can you tell me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you tell me please how did you create this HDATextTool program? How did you extract content of .bin and .txt files?

**Comment by Species-8472** [comment]
Can you tell me please how did you create this HDATextTool program? How did you knew it has content of .bin and .txt files?

**Comment by Species-8472** [comment]
Can you tell me please how did you create this HDATextTool program? How did you knew it has content of .bin and .txt files?

**Comment by Species-8472** [comment]
Can you tell me please how did you create this HDATextTool program? How did you knew it has content of .bin and .txt files?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by Species-8472** [comment]
Can you please explain me please how did you create this HDATextTool program?

**Comment by gdkchan** [comment]
Closing since #6 is supposed to address the same thing.
