### ISSUE TITLE
Can you update HDATextTool to accept symbols not just letters

### ISSUE THREAD

**Issue by Tim1212** [gdkchan/HDATextTool#7]
Can you update the tool so it can write not only letters, so you can put other characters like symbols into the text you want to change?

**Comment by gdkchan** [comment]
To do this you need to edit the font (I think it's inside a file called, well, FONT.HDA). You can edit it using one of those editors, I don't remember the format but isn't hard to figure out. Then after editing the font you recreate the HDA, inserts into the game and adds the new symbol values on the CharacterTable.txt and recompile the program.

**Comment by Tim1212** [comment]
I tryed to insert new symbols to Character Table.txt and changed for japaneese letters, but it doesn't work... Like they are missplaced in the changed text, after i import it to .bin and export it back.. pls help

**Comment by gdkchan** [comment]
Like I said you need to edit the game font AND edit the character table with the hex value for the corresponding symbol on the font and the symbol. Otherwise it won't work.

**Comment by Tim1212** [comment]
Ok, can you tell me to edit the FONT.HDA? thanks

**Comment by Tim1212** [comment]
Ok, can you pls just tell me how to edit the FONT.HDA?

**Comment by Tim1212** [comment]
I don't understand... pls help

**Comment by Tim1212** [comment]
Can you tell me how to edit font? thanks

**Comment by Tim1212** [comment]
I was trying this for hours and didn't get it at all... can you tell me how to edit the game font? thanks

**Comment by Tim1212** [comment]
Please tell me, because when i try to edit font and use -xhda on FONT.HDA and -xtxt i get File_00000.bin and File_00001.bin, i get blank text.txt File with no text.

**Comment by gdkchan** [comment]
Closing this since for some reason you opened issue #8 to discuss the same thing.
