### ISSUE TITLE
How to edit font to get symbol in game?

### ISSUE THREAD

**Issue by Tim1212** [gdkchan/HDATextTool#8]
I know everything, and recreated character table.txt with new symbols, recompiled the program, but I don't know how to edit FONT.HDA to get symbol in game, can you help me?

**Comment by gdkchan** [comment]
Extract the FONT.HDA file on CGDATA\COMMON, it will create two files on the extracted folder, File_00000.bin and File_00001.bin. Now you can open File_00000.bin on a tile editor such as TileMolester. To do this open the program, click on the folder icon to show the open dialog, on file type select all files, then open the bin file. You'll probably see some garbled graphics. Go to View -> Mode -> 2-Dimensional. Then go to View -> Codec -> 2bpp linear reverse-order. Now keep clicking on the |||< decrease width icon until the image is only 1 column wide and you can see the characters perfectly. They will be mirrored through.

You can then pick a character you don't need on the font and replace it with the one you need (for example, you probably don't need the hiragana/katakana charset so you can just replace that). After you finish editing the font you can use the Save option on the tile editor, then re-create the FONT.HDA file using this tool, and inserting it on the game image.

The last step is replacing the respective character on CharacterTables.txt on this tool aswell, after doing that you can start editing texts using your new characters.

For further questions about this kind of stuff I recommend you asking on a dedicated forum such as [ROMHacking Forums](http://www.romhacking.net/forum/). Peharps they even know better tools than the one I suggested here. I rarely do translations nowadays so I'm not very up-to-date with this kind of stuff.

**Comment by Tim1212** [comment]
Thank you very much! Hope there will be more tools like this one, it's a great tool!

**Comment by gdkchan** [comment]
if you look on the left side of the program youll see a toolbar with some tools you can use to edit the font. Like selection, pencil, bucket fill, this kind of stuff. And at the bottom you will find the palette colors. You need to use the same coloring used on the other characters (like... one colors is for the character, other for the outlines shading...)

You probably can copy/paste from other images too, but I never tried that. And it probably won't look very good, so it's better to do it manually.

**Comment by gdkchan** [comment]
Guess that the issue was resolved so closing this aswell.
